[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ndetect"
version = "0.1.0"
description = "A CLI tool for detecting near-duplicate text files using MinHash"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "datasketch>=1.5.0",  # For MinHash implementation
    "rich>=13.0.0",       # For interactive CLI interface
]

[project.scripts]
ndetect = "ndetect.cli:main"

[tool.setuptools.packages.find]
include = ["ndetect*"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.mypy]
python_version = "3.12"
strict = true 

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=24.0.0",
    "mypy>=1.8.0",
    "ruff>=0.2.0",
] 