import numpy as np
from numpy.typing import NDArray

class MinHash:
    def __init__(self, num_perm: int = 128) -> None: ...
    def update(self, b: bytes) -> None: ...
    def digest(self) -> NDArray[np.uint64]: ...
    def jaccard(self, other: "MinHash") -> float: ... 